#ifndef PROJECT_SO_SUPPORT_H
#define PROJECT_SO_SUPPORT_H

#define ARRAY_SIZE 11

#define SO_BLOCK_SIZE 10
#define SO_REGISTRY_SIZE 15

#define SO_USERS_NUM 0
#define SO_NODES_NUM 1
#define SO_BUDGET_INIT 2
#define SO_REWARD 3
#define SO_MIN_TRANS_GEN_NSEC 4
#define SO_MAX_TRANS_GEN_NSEC 5
#define SO_RETRY 6
#define SO_TP_SIZE 7
#define SO_MIN_TRANS_PROC_NSEC 8
#define SO_MAX_TRANS_PROC_NSEC 9
#define SO_SIM_SEC 10

#define MAX_VALUE 1

#define TIME_SIMULATION 0

#endif